=== JulenSalinas/MovieServe/RETO2/XSD Y XML/Clientes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="clientes">
        <!--Encima de este comentario, introducimos la dos primeras líneas que debe tener nuestro archivo .xsd y debajo de las mismas, creamos el elemento padre llamado clientes-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name ="cliente" maxOccurs="unbounded"> <!--Creamos el elemento clientes con el maxOccurs unbounded para poder introducir más de una etiqueta cliente en el xml-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name ="Telefono"> <!--Creamos el elemento de Telefono-->
                                <xs:simpleType>
                                    <xs:restriction base ="xs:integer"><!--Creamos una restricción tipo integer, tambien, el total de dígitos debe de ser 9-->
                                        <xs:totalDigits value="9"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name ="Nombre" type="xs:string"/>  <!--Creamos el elemento Nombre y Apellido de tipo String-->
                            <xs:element name ="Apellido" type="xs:string"/>
                            <xs:element name ="DNI"><!--Creamos el elemento DNI-->
                                <xs:simpleType>
                                    <xs:restriction base = "xs:string"><!--Creamos una restricción tipo String y el patrón es el que tenemos que introducir para que concuerde con un DNI-->
                                        <xs:pattern value="[0-9]{8}[A-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name ="Email"> <!--Creamos el elemento de Email-->
                                <xs:simpleType>
                                    <xs:restriction base = "xs:string"><!--Creamos una restricción tipo String y el patrón es el que tenemos que introducir para que concuerde con un Email-->
                                        <xs:pattern value = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name = "pelicula"><!--Creamos el elemento de pelicula-->
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name = "peliculaAVer"><!--Creamos el elemento de peliculaAVer e insertamos todos los nombres de las películas en una restricción tipo string y con varios enumeration-->
                                            <xs:simpleType>
                                                <xs:restriction base = "xs:string">
                                                    <xs:enumeration value="El regreso de Jaava"/>
                                                    <xs:enumeration value="La BakQ perdida"/>
                                                    <xs:enumeration value="Las aventuras de Inti: El duende de Garbera"/>
                                                    <xs:enumeration value="Tamayo:El escape"/>
                                                    <xs:enumeration value="Programación eterna"/>
                                                    <xs:enumeration value="El gasto"/>
                                                    <xs:enumeration value="Asesinato en la máquina virtual"/>
                                                    <xs:enumeration value="El Break"/>
                                                    <xs:enumeration value="La ley prohibida"/>
                                                    <xs:enumeration value="El arte de la doma clásica"/>
                                                    <xs:enumeration value="El Wuekii"/>
                                                    <xs:enumeration value="El trén de vuelta"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name ="Genero" type ="generoType" use ="required"/><!--Creamos el atributo llamado Genero y de uso requerido-->
                                    <xs:attribute name ="Duracion" type ="duracionType" use ="required"/><!--Creamos el atributo llamado Duracion y de uso requerido-->
                                    <xs:attribute name ="id_Sala" type ="id_SalaType" use = "required"/><!--Creamos el atributo llamado id_Sala y de uso requerido-->
                                    <xs:attribute name ="id_Pelicula" type ="id_PeliculaType" use = "required"/><!--Creamos el atributo llamado id_Pelicula y de uso requerido-->
                                </xs:complexType>
                            </xs:element>

                            <xs:element name = "cantidadAsientos"><!--Creamos el elemento de cantidadAsientos-->
                                <xs:simpleType>
                                    <xs:restriction base = "xs:integer"><!--Creamos una restricción tipo integer, tambien,especificamos un minExclusive y un maxInclusive para indicar el mácimo y mínimo de los asientos disponibles-->
                                        <xs:minExclusive value="0"/>
                                        <xs:maxInclusive value="260"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name ="Fecha" type = "xs:date"/><!--Añadimos el campo Fecha de tipo date-->
                        </xs:sequence>
                        <xs:attribute name="idCliente" type ="idclienteType" use ="required"/><!--Creamos el atributo llamado idCLiente de uso requerido-->
                    </xs:complexType>
                </xs:element>
                

            </xs:sequence>
        </xs:complexType>
    </xs:element>

<!--Añadimos las restricciones de cada type de los atributos antes mencionados-->
    <xs:simpleType name="idclienteType">
        <xs:restriction base="xs:integer">  <!--Restricción tipo integer e indicamos con un minExclusive que el idCliente no puede ser 0 y tiene que ser mayor de eso-->
          <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="generoType"><!--Restricción tipo String e indicamos con una serie de enumeration con los géneros de las películas-->
        <xs:restriction base="xs:string"> 
          <xs:enumeration value="Terror"/>
          <xs:enumeration value="Fantasía"/>
          <xs:enumeration value="Aventura"/>
          <xs:enumeration value="Thriller psicológico"/>
          <xs:enumeration value="Suspense"/>
          <xs:enumeration value="Drama"/>
          <xs:enumeration value="Comedia"/>
          <xs:enumeration value="Tragedia"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="duracionType"> <!--Restricción tipo integer e indicamos con un minExclusive que el valor ha de ser mayor que 60-->
        <xs:restriction base="xs:integer"> 
          <xs:minInclusive value="60"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id_SalaType"><!--Restricción tipo integer e indicamos con un minExclusive y un maxInclusive que el valor tiene que ser mayor a 0 y menor o igual a 8-->
        <xs:restriction base="xs:integer"> 
          <xs:minExclusive value="0"/>
          <xs:maxInclusive value="8"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id_PeliculaType"><!--Restricción tipo integer e indicamos con un minExclusive y un maxInclusive que el valor tiene que ser mayor a 0 y menor o igual a 12-->
        <xs:restriction base="xs:integer"> 
          <xs:minExclusive value="0"/>
          <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== JulenSalinas/MovieServe/RETO2/XSD Y XML/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clientes.xsd">
    <cliente idCliente = "1">
        <Telefono>653419603</Telefono>
        <Nombre>Paco</Nombre>
        <Apellido>Gutierrez</Apellido>
        <DNI>19391645P</DNI>
        <Gmail>paco@gmail.com</Gmail>
        <pelicula Genero = "Terror" Duracion = "134" id_Sala ="3" id_Pelicula = "7">
            <peliculaAVer>Asesinato en la máquina virtual</peliculaAVer>
        </pelicula>
            <cantidadAsientos>5</cantidadAsientos>
    </cliente>

    <cliente idCliente = "2">
        <Telefono>618534289</Telefono>
        <Nombre>Eugenia</Nombre>
        <Apellido>Dominguez</Apellido>
        <DNI>00816387E</DNI>
        <Gmail>dominguez@gmail.com</Gmail>
        <pelicula Genero = "Aventura" Duracion = "90"  id_Sala ="7" id_Pelicula = "2">
            <peliculaAVer>La BakQ perdida</peliculaAVer>
        </pelicula>
            <cantidadAsientos>2</cantidadAsientos>
    </cliente>

    <cliente idCliente = "3">
        <Telefono>610035701</Telefono>
        <Nombre>Claudia</Nombre>
        <Apellido>Gutierrez</Apellido>
        <DNI>12389013B</DNI>
        <Gmail>guti@gmail.com</Gmail>
        <pelicula Genero = "Suspense" Duracion = "92" id_Sala ="2" id_Pelicula = "9">
            <peliculaAVer>La ley prohibida</peliculaAVer>
        </pelicula>
            <cantidadAsientos>1</cantidadAsientos>
    </cliente>

    <cliente idCliente = "4">
        <Telefono>609863401</Telefono>
        <Nombre>Clara</Nombre>
        <Apellido>Navarro</Apellido>
        <DNI>98156329U</DNI>
        <Gmail>navarro@gmail.com</Gmail>
        <pelicula Genero = "Drama" Duracion = "79" id_Sala ="1" id_Pelicula = "8">
            <peliculaAVer>El Break</peliculaAVer>
        </pelicula>
            <cantidadAsientos>4</cantidadAsientos>
    </cliente>

    <cliente idCliente = "5">
        <Telefono>611826432</Telefono>
        <Nombre>Miguel</Nombre>
        <Apellido>Moreno</Apellido>
        <DNI>12973970V</DNI>
        <Gmail>miguel@gmail.com</Gmail>
        <pelicula Genero = "Fantasía" Duracion = "120" id_Sala ="8" id_Pelicula = "1">
            <peliculaAVer>El regreso de Jaava</peliculaAVer>
        </pelicula>
            <cantidadAsientos>3</cantidadAsientos>
    </cliente>

    <cliente idCliente = "6">
        <Telefono>652910351</Telefono>
        <Nombre>Emilio</Nombre>
        <Apellido>Abichuela</Apellido>
        <DNI>10238447A</DNI>
        <Gmail>abichu@gmail.com</Gmail>
        <pelicula Genero = "Fantasía" Duracion = "84" id_Sala ="6" id_Pelicula = "11">
            <peliculaAVer>El Wuekii</peliculaAVer>
        </pelicula>
            <cantidadAsientos>6</cantidadAsientos>
    </cliente>

    <cliente idCliente = "7">
        <Telefono>619926745</Telefono>
        <Nombre>Luna</Nombre>
        <Apellido>Perez</Apellido>
        <DNI>44789135T</DNI>
        <Gmail>luna@gmail.com</Gmail>
        <pelicula Genero = "Thriller psicológico" Duracion = "150" id_Sala ="5" id_Pelicula = "5">
            <peliculaAVer>Programación eterna</peliculaAVer>
        </pelicula>
            <cantidadAsientos>3</cantidadAsientos>
    </cliente>

    <cliente idCliente = "8">
        <Telefono>639910835</Telefono>
        <Nombre>Erling</Nombre>
        <Apellido>Haaland</Apellido>
        <DNI>27729189S</DNI>
        <Gmail>erling@gmail.com</Gmail>
        <pelicula Genero = "Suspense" Duracion = "98" id_Sala ="4" id_Pelicula = "6">
            <peliculaAVer>El gasto</peliculaAVer>
        </pelicula>
            <cantidadAsientos>4</cantidadAsientos>
    </cliente>

    <cliente idCliente = "9">
        <Telefono>623091742</Telefono>
        <Nombre>Sergio</Nombre>
        <Apellido>Ramos</Apellido>
        <DNI>57659201D</DNI>
        <Gmail>mushoarte@gmail.com</Gmail>
        <pelicula Genero = "Fantasía" Duracion = "84" id_Sala ="7" id_Pelicula = "11">
            <peliculaAVer>El Wuekii</peliculaAVer>
        </pelicula>
            <cantidadAsientos>1</cantidadAsientos>
    </cliente>

    <cliente idCliente = "10">
        <Telefono>639830913</Telefono>
        <Nombre>Alberto</Nombre>
        <Apellido>Chicote</Apellido>
        <DNI>88727112J</DNI>
        <Gmail>croquetas@gmail.com</Gmail>
        <pelicula Genero = "Terror" Duracion = "138" id_Sala ="2" id_Pelicula = "12">
            <peliculaAVer>El trén de vuelta</peliculaAVer>
        </pelicula>
            <cantidadAsientos>1</cantidadAsientos>
    </cliente>


</clientes>

=== JulenSalinas/MovieServe/RETO2/Grupo A/XSD Y XML/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clientes.xsd">
    <!--Arriba ponemos la primera línea de cualquier archivo xml, debajo de esta indicamos a que esquema xsd se concecta y abrimos la etiqueta padre llamada clientes-->
    <cliente idCliente = "21">
        <Telefono>+97291730</Telefono> <!--Algunos datos de teléfono llevan un + para ver que se puede introducir de tal manera, en cambio hay otros que no por el mismo echo-->
        <Nombre>Paco</Nombre> <!--Insertamos el nombre Paco-->
        <Apellido>Alcacer</Apellido><!--Insertamos el apellido Alcacer-->
        <DNI>28635151S</DNI> <!--Insertamos el DNI-->
        <Email>alcacer@hotmail.es</Email> <!--Insertamos el Correo-->
        <pelicula Genero = "Drama" Duracion = "79" id_Sala ="8" id_Pelicula = "8"> <!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El Break</peliculaAVer> <!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>4</cantidadAsientos> <!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-07</Fecha> <!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "22">
        <Telefono>+97291731</Telefono><!--Insertamos el teléfono-->
        <Nombre>Gabriel</Nombre><!--Insertamos el nombre Gabriel-->
        <Apellido>Jesus</Apellido><!--Insertamos el apellido Jesus-->
        <DNI>28635154T</DNI> <!--Insertamos el DNI-->
        <Email>gabriel@hotmail.com</Email> <!--Insertamos el Correo-->
        <pelicula Genero = "Aventura" Duracion = "90"  id_Sala ="2" id_Pelicula = "2"> <!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>La BakQ perdida</peliculaAVer> <!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>2</cantidadAsientos> <!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-09</Fecha> <!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "23">
        <Telefono>+982470091</Telefono><!--Insertamos el teléfono-->
        <Nombre>Berta</Nombre><!--Insertamos el nombre Berta-->
        <Apellido>Escobar</Apellido><!--Insertamos el apellido Escobar-->
        <DNI>20018938E</DNI><!--Insertamos el DNI-->
        <Email>gescobar@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Terror" Duracion = "134" id_Sala ="7" id_Pelicula = "7"> <!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>Asesinato en la máquina virtual</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>7</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-06</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "34">
        <Telefono>609863401</Telefono><!--Insertamos el teléfono-->
        <Nombre>Clara</Nombre><!--Insertamos el nombre Clara-->
        <Apellido>Navarro</Apellido><!--Insertamos el apellido Navarro-->
        <DNI>98156329U</DNI><!--Insertamos el DNI-->
        <Email>navarro@gmail.com</Email> <!--Insertamos el Correo-->
        <pelicula Genero = "Drama" Duracion = "79" id_Sala ="8" id_Pelicula = "8"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El Break</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>4</cantidadAsientos>
        <Fecha>2024-02-03</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "35">
        <Telefono>+611826432</Telefono><!--Insertamos el teléfono-->
        <Nombre>Miguel</Nombre><!--Insertamos el nombre Miguel-->
        <Apellido>Moreno</Apellido><!--Insertamos el apellido Moreno-->
        <DNI>12973970V</DNI><!--Insertamos el DNI-->
        <Email>miguel@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Fantasía" Duracion = "120" id_Sala ="1" id_Pelicula = "1"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El regreso de Jaava</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>3</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-08</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "36">
        <Telefono>652910351</Telefono><!--Insertamos el teléfono-->
        <Nombre>Emilio</Nombre><!--Insertamos el nombre Emilio-->
        <Apellido>Abichuela</Apellido><!--Insertamos el apellido Abichuela-->
        <DNI>10238447A</DNI><!--Insertamos el DNI-->
        <Email>abichu@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Fantasía" Duracion = "84" id_Sala ="3" id_Pelicula = "11"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El Wuekii</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>6</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-04</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "37">
        <Telefono>619926745</Telefono><!--Insertamos el teléfono-->
        <Nombre>Luna</Nombre><!--Insertamos el nombre Luna-->
        <Apellido>Perez</Apellido><!--Insertamos el apellido Perez-->
        <DNI>44789135T</DNI><!--Insertamos el DNI-->
        <Email>luna@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Thriller psicológico" Duracion = "150" id_Sala ="5" id_Pelicula = "5"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>Programación eterna</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>3</cantidadAsientos>
        <Fecha>2024-02-05</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "38">
        <Telefono>639910835</Telefono><!--Insertamos el teléfono-->
        <Nombre>Erling</Nombre><!--Insertamos el nombre Erling-->
        <Apellido>Haaland</Apellido><!--Insertamos el apellido Haaland-->
        <DNI>27729189S</DNI><!--Insertamos el DNI-->
        <Email>erling@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Suspense" Duracion = "98" id_Sala ="6" id_Pelicula = "6"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El gasto</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>4</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-07</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "39">
        <Telefono>623091742</Telefono><!--Insertamos el teléfono-->
        <Nombre>Sergio</Nombre><!--Insertamos el nombre Sergio-->
        <Apellido>Ramos</Apellido><!--Insertamos el apellido Ramos-->
        <DNI>57659201D</DNI><!--Insertamos el DNI-->
        <Email>mushoarte@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Fantasía" Duracion = "84" id_Sala ="3" id_Pelicula = "11"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El Wuekii</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>1</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-06</Fecha><!--Insertamos la fecha-->
    </cliente>

    <cliente idCliente = "40">
        <Telefono>639830913</Telefono><!--Insertamos el teléfono-->
        <Nombre>Alberto</Nombre><!--Insertamos el nombre Alberto-->
        <Apellido>Chicote</Apellido><!--Insertamos el apellido Chicote-->
        <DNI>88727112J</DNI><!--Insertamos el DNI-->
        <Email>croquetas@gmail.com</Email><!--Insertamos el Correo-->
        <pelicula Genero = "Terror" Duracion = "138" id_Sala ="4" id_Pelicula = "12"><!--Insertamos los atributos de las películas incluyendo los id de sala , id pelicula,Genero y Duracion-->
            <peliculaAVer>El trén de vuelta</peliculaAVer><!--Insertamos el nombre de la película-->
        </pelicula>
        <cantidadAsientos>1</cantidadAsientos><!--Insertamos la cantidad de asientos-->
        <Fecha>2024-02-09</Fecha><!--Insertamos la fecha-->
    </cliente>


</clientes><!--Cerramos la etiqueta padre llamada clientes-->
